### ISSUE TITLE
can not find libpluie

### ISSUE THREAD

**Issue by shuluoshu** [scenenn/pointwise#1]
In modelnet_provider.py , I cannot find the libpluie (Line 9), do you forget to include that file ?

**Comment by songuke** [comment]
@shuluoshu Thanks for raising the issue. Libpluie is just a custom library we made to parse point clouds and do some Morton sorting. If you just use sorting according to XYZ coordinates and do not need visualization, you do not need libpluie in our code, and please simply comment them out. 

I will release a version that is runnable soon. Stay tuned!

**Comment by songuke** [comment]
@shuluoshu libpluie is now not required to run the code. Please update your repository.
