### ISSUE TITLE
ply to hdf5

### ISSUE THREAD

**Issue by STARBOYsachin** [scenenn/pointwise#16]
Hey how do you convert the .ply files in original dataset(3DV 2016 (original instance annotation of 100+ scenes)) to hdf5(CVPR 2018 (evaluating semantic segmentation with NYU-D v2 40 classes))

**Comment by songuke** [comment]
Hi, we had an in-house C++ library tied to Python so that we can iterate and parse the scenes from PLY, downsample the points, divide them into blocks, and store the results to HDF5. We did some additional checks and discarded point clouds that are empty or having too few points in the block.

**Comment by STARBOYsachin** [comment]
Any script for that conversion?
I want to create some of my own data files, annotate  and add to training data.

**Comment by songuke** [comment]
Please email me at binhson.hua at gmail. I will send the script to you.
