### ISSUE TITLE
unable to compile tf_ops

### ISSUE THREAD

**Issue by Saira05** [scenenn/pointwise#2]
i am facing this error when i compile "tf_conv3p_compile_.sh". kindly guide me if i am doing something wrong? 

$chmod a+x *
$ ./tf_conv3p_compile_.sh
/home/sarshad/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
gcc: error: .cu: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
g++: error: .cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: error: .cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:32,
                 from tf_conv3p_grid.cpp:1:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:32,
                 from tf_conv3p_naive_ctxmem.cu:1:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:32,
                 from register_op.cpp:1:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.
g++: error: tf_conv3p.so_cuda.o: No such file or directory
g++: error: tf_conv3p.so_cpu.o: No such file or directory
rm: cannot remove 'tf_conv3p.so_cpu.o': No such file or directory
rm: cannot remove 'tf_conv3p.so_cuda.o': No such file or directory

**Comment by dangjisheng** [comment]
Have you solve this problem?I also meet this problem.Can you help me?

**Comment by saira05** [comment]
If you are using tensorflow 1.4 then please compile the tf_conv3p_compile_tf14.sh and other details you can find in Readme.

**Comment by dangjisheng** [comment]
My tensorflow'version is 1.4,there are my error:


raceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
tf_conv3p_grid.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
nvcc fatal   : argument expected after '-I'
register_op.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
g++: error: register_op.o: No such file or directory
g++: error: tf_conv3p.so_cuda.o: No such file or directory
g++: error: tf_conv3p.so_cpu.o: No such file or directory
rm: cannot remove 'tf_conv3p.so_cpu.o': No such file or directory
rm: cannot remove 'tf_conv3p.so_cuda.o': No such file or directory


------------------ 原始邮件 ------------------
发件人: "saira05"<notifications@github.com>;
发送时间: 2019年5月25日(星期六) 凌晨2:53
收件人: "scenenn/pointwise"<pointwise@noreply.github.com>;
抄送: "雄途～～～"<1442342449@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [scenenn/pointwise] unable to compile tf_ops (#2)




If you are using tensorflow 1.4 then please compile the tf_conv3p_compile_tf14.sh and other details you can find in Readme.
