### ISSUE TITLE
tensorflow TypeError when applying the GPU conv3p operator

### ISSUE THREAD

**Issue by YukiRain** [scenenn/pointwise#5]
I'm trying to use the GPU version of the conv3p operator, so I set the parameter "use_gpu" to true in the file "param.json". However, the following issue occurred when running the Python code "train_modelnet40_acsd.py":
`/python3.5/site-packages/tensorflow/python/framework/ops.py
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.`
It seems that this may not be a problem in the Python codes. Is there anything wrong with the GPU compilation, or I'm incorrectly use the codes?

**Comment by songuke** [comment]
When compiling the custom convolution operator, did you execute 
`./tf_conv3p_compile.sh -a`
with the `-a` flag to activate atrous convolution? 

The signature of the non-atrous and atrous convolution are different. 

By default, the network model in train_modelnet40_acsd assumes atrous convolution.

**Comment by YukiRain** [comment]
Thanks!!! My neglicence.
Very interesting project and nice idea. I learn a lot from the CUDA codes.
👍
